config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"

  resources :users do
    member do
      get "friendlist", as: "friendlist"
    end
    member do
      get "viewed_documents"
    end
    member do
      get "downloaded_documents"
    end
  end

  resources :documents do
    member do
      get "download_pdf"
    end
  end
  
  resources :comments
  resources :requests
  resources :histories
  resources :categories
  resources :category_relationships
  resources :follow_relationships
  resources :favorites, only: [:create, :destroy]

  namespace :admin do
    resources :requests, only: [:index, :update]
    resources :users do
      member do
        patch :update_role, as: "update_role"
        get "reason", as: "reason"
      end
    end
  end

  root "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :comments
  has_many :documents
  has_many :favorites
  has_many :favorite_documents, through: :favorites, source: :document
  has_many :follow_relationships
  has_many :histories
  has_many :viewed_documents, through: :histories, source: :document
  has_many :downloaded_times
  has_many :downloaded_documents, through: :downloaded_times, source: :document
  has_many :requests

  has_many :active_relationships, class_name: "FollowRelationship",
                                foreign_key: :following_id,
                                dependent: :destroy
  has_many :followed, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "FollowRelationship",
                                 foreign_key: :followed_id,
                                 dependent: :destroy
  has_many :following, through: :passive_relationships, source: :following

  has_many :active_friends, -> {where(status: "accepted")},
                            class_name: "FollowRelationship",
                            foreign_key: :following_id
  has_many :followed_friends, through: :active_friends, source: :followed
  has_many :passive_friends, -> {where status: "accepted"},
                             class_name: "FollowRelationship",
                             foreign_key: :followed_id
  has_many :following_friends, through: :passive_friends, source: :following


  has_one_attached :avatar

  acts_as_paranoid

  validates :name, presence: true, length: {maximum: 100}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 120},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:destroy]

  def update_role
  request = Request.find(params[:id])
  @user = request.user
    if @user.update_attribute(:reason, params[:user][:reason])
      @user.update_attribute(:requested, "rejected")
      redirect_to @user
      request.delete
      flash[:success] = "done"
    else
      redirect_to requests_path
      flash[:danger] = "not done"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def check_admin
    unless current_user.role == "admin"
      redirect_to root_path
      flash[:danger] = "Fuck off"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create, :friendlist, :index]
  before_action :correct_user, only: [:edit, :update]
  before_action :check_admin, only: [:destroy]
  skip_before_action :check_if_logged_in, only: [:new, :create]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      log_in @user
      redirect_to @user
      flash[:success] = "Welcome to the gang"
    else
      render "new"
    end
  end

  def edit
    #code
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
      flash[:success] = "Profile updated"
    else
      redirect_to @user
      flash[:danger] = "Profile note updated"
    end
  end

  def show
    @user = User.find(params[:id])
    @viewed_documents = @user.viewed_documents
    @friend_request = current_user.active_relationships.find_by(following_id: current_user.id,
                                                                followed_id: @user.id)
    @downloaded_documents = current_user.downloaded_documents
  end

  def destroy
    #code for banning?
  end

  def friendlist
    @friends = current_user.following_friends + current_user.followed_friends
  end

  def viewed_documents
    @viewed_documents = @user.viewed_documents.paginate(
      page: params[:page],
      per_page: 24
    )
  end

  def downloaded_documents
    @downloaded_documents = @user.downloaded_documents.paginate(
      page: params[:page],
      per_page: 24
    )
  end
  private

  def users_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    unless @user == current_user
      respond_to do |format|
        format.html {redirect_to users_url, notice: "Mind your own business boi"}
      end
    end
  end

  def check_admin
    unless current_user.role == "admin"
      redirect_to root_path
      flash[:danger] = "Fuck off"
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/downloaded_documents.html.erb
<h2>Documents I have downloaded</h2>
<%= will_paginate @downloaded_documents %>
<div class="row">
  <% @downloaded_documents.each do |d| %>
    <div class="col-2">
      <div class="card">
        <%= image_tag d.file_name.preview(size: "50x50"), class: "card-img-top" %>
        <div class="card-body">
          <p>Description: <%= d.description %></p>
          <p>Author: <%= d.author %></p>
          <p><%= d.view_count %> views</p>
          <p><%= d.download_count %> downloads</p>
          <p><%= link_to "document show", d %></p>
          <p><%= link_to "Download this document", download_pdf_document_path(d), target: "blank" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/friendlist.html.erb
<h1>Mah friendz</h1>
<div class="container">
  <table>
    <% @friends.each do |n| %>
      <tr>
        <td>
          <p><%= image_tag n.avatar, size: '192x108' %> <%= link_to n.name, n %></p>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= will_paginate %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Show", user %></td>
        <td><%= link_to "Destroy", user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if user == current_user %>
          <td><%= link_to "Edit", edit_user_path(user) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 style="text-align: center">Create an account</h1>
<div class="row justify-content-center">
  <div class="col-6">
    <div class="form-group">
      <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.label :avatar %>
        <%= f.file_field :avatar %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Profile</h1>

<%= render "follow_relationships/follow-form" %>
<% if @user == current_user %>
  <p><%= link_to "All friend requests", follow_relationships_path, class: "btn btn-primary" %></p>
<% end %>

<p><%= link_to "Friendlist", friendlist_user_path, class: "btn btn-primary" %></p>

<div class="row">
  <div class="col-3">
    <div class="card" style="inline">
      <%= image_tag @user.avatar, size: '200', class: "card-img-top" %>
      <div class="card-body">
        <h2><%= @user.name %></h2>
      </div>
    </div>
  </div>
</div>

<% if @viewed_documents %>
  <h2>Documents I have viewed</h2>
  <div class="row">
    <% @viewed_documents.each do |d| %>
      <div class="col-2">
        <div class="card">
          <%= image_tag d.file_name.preview(size: "50x50"), class: "card-img-top" %>
          <div class="card-body">
            <p>Description: <%= d.description %></p>
            <p>Author: <%= d.author %></p>
            <p><%= d.view_count %> views</p>
            <p><%= d.download_count %> downloads</p>
            <p><%= link_to "document show", d %></p>
            <p><%= link_to "Download this document", download_pdf_document_path(d), target: "blank" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<h2>Documents I have downloaded</h2>
<div class="row">
  <% @downloaded_documents.each do |d| %>
    <div class="col-2">
      <div class="card">
        <%= image_tag d.file_name.preview(size: "50x50"), class: "card-img-top" %>
        <div class="card-body">
          <p>Description: <%= d.description %></p>
          <p>Author: <%= d.author %></p>
          <p><%= d.view_count %> views</p>
          <p><%= d.download_count %> downloads</p>
          <p><%= link_to "document show", d %></p>
          <p><%= link_to "Download this document", download_pdf_document_path(d), target: "blank" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/viewed_documents.html.erb
<h2>Documents I have viewed</h2>
<%= will_paginate @viewed_documents %>
<div class="row">
  <% @viewed_documents.each do |d| %>
    <div class="col-2">
      <div class="card">
        <%= image_tag d.file_name.preview(size: "50x50"), class: "card-img-top" %>
        <div class="card-body">
          <p>Description: <%= d.description %></p>
          <p>Author: <%= d.author %></p>
          <p><%= d.view_count %> views</p>
          <p><%= d.download_count %> downloads</p>
          <p><%= link_to "document show", d %></p>
          <p><%= link_to "Download this document", download_pdf_document_path(d), target: "blank" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>