config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"

  resources :users do
    member do
      get "friendlist", as: "friendlist"
    end
    member do
      get "viewed_documents"
    end
    member do
      get "downloaded_documents"
    end
  end

  resources :documents do
    member do
      get "download_pdf"
    end
  end
  
  resources :comments
  resources :requests
  resources :histories
  resources :categories
  resources :category_relationships
  resources :follow_relationships
  resources :favorites, only: [:create, :destroy]

  namespace :admin do
    resources :requests, only: [:index, :update]
    resources :users do
      member do
        patch :update_role, as: "update_role"
        get "reason", as: "reason"
      end
    end
  end

  root "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  has_many :category_relationships
  has_many :categories, through: :category_relationships
  has_many :comments
  has_many :downloaded_times
  has_many :downloaders, through: :downloaded_times, source: :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user
  has_many :histories
  has_many :users, through: :histories

  has_one_attached :file_name

  belongs_to :user

  acts_as_paranoid

  validate :correct_document_mime_type

  private

  def correct_document_mime_type
    if file_name.attached? && !file_name.content_type.in?(%w(application/pdf))
      file_name.purge
      errors.add(:file_name, 'Must be a PDF file')
    end
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:edit, :update, :show, :destroy, :download_pdf]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @documents = current_user.documents.all
  end

  def new
    @document = current_user.documents.build
  end

  def create
    @document = current_user.documents.build(document_params)
    if @document.save!
      @document.file_name.attach(params[:document][:file_name])
      redirect_to @document
      flash[:success] = "File uploaded!"
    else
      render :new
    end
  end

  def show
    @document = Document.find(params[:id])
    @history = History.find_by(user_id: current_user.id, document_id: @document.id)
    @downloaded_time = DownloadedTime.find_by(user_id: current_user.id, document_id: @document.id)
    if @history
      @history.update_attribute(:counter, @history.counter + 1)
    else
      @history = History.create(document_id: @document.id, user_id: current_user.id, counter: 1)
    end

    @total_view = History.where(document_id: @document.id).sum(:counter)
    @document.update_attribute(:view_count, @total_view)

    @total_download_count = DownloadedTime.where(document_id: @document.id).sum(:count)
    @document.update_attribute(:download_count, @total_download_count)

    @is_read = @document.histories.where(user_id: current_user.id).exists?
    @is_downloaded = @document.downloaded_times.where(user_id: current_user.id).exists?
  end

  def edit
    #code
  end

  def update
    if @document.update_attributes(document_params)
      redirect_to @document
      flash[:success] = "Document updated"
    else
      redirect_to @document
      flash[:danger] = "Document not updated"
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path
    flash[:success] = "Doc deleted"
  end

  def download_pdf
    this_doc_download_time = @document.downloaded_times.find_by(user_id: current_user.id)
    if this_doc_download_time
      this_doc_download_time.update_attribute(:count, this_doc_download_time.count + 1)
    else
      @document.downloaded_times.create(user_id: current_user.id, count: 1)
    end
    send_data @document.file_name.download, filename: @document.file_name.filename.to_s,
      content_type: @document.file_name.content_type
  end

  private

  def document_params
    params.require(:document).permit(:file_name, :description, :author, category_ids: [])
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def correct_user
    unless @document.user == current_user
      respond_to do |format|
        format.html {redirect_to root_path, notice: "Mind your own business boi"}
      end
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_favorite_form.html.erb
<!-- <% if @document == current_user.favorite_documents.find_by(id: @document_id) %>
  <%= button_to "Added to favorite", action: :new, class: "btn" %>
<% else %>
  <%= form_for(:favorites, url: favorites_path, method: :post) do |f| %>
    <%= f.hidden_field :document_id, value: @document.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Add to favorite", class: "btn btn-primary" %>
  <% end %>
<% end %> -->

<%# TODO: above %>

app/views/documents/_profile-form.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <div class="form-group">
      <%= form_for(@document) do |f| %>
        <%= f.label :author %>
        <%= f.text_field :author, class: "form-control" %>

        <%= f.label :description  %>
        <%= f.text_field :description, class: "form-control" %>

        <%= f.label :file_name %>
        <%= f.file_field :file_name, class: "form-control" %>

        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :category) %>

        <%= f.submit yield(:button_text), class: "btn btn-primary" %>

      <% end %>
    </div>
  </div>
</div>

app/views/documents/edit.html.erb
<h1 style="text-align: center">Edit document</h1>
<% provide(:button_text, "Update my document") %>
<%= render "profile-form" %>

app/views/documents/index.html.erb
<h1>Your documents</h1>
<% @documents.each do |p| %>
  <div class="panel panel-default", style="padding: 15px 40px">
    <p><%# image_tag @document.file_name.preview(size: "200x400") %></p>
    <h3><%= p.description %></h3>
    <p><%= p.author %></p>

    <p>
      <small><%= link_to "Edit", "#" %></small>
      <small><%= link_to "Show", p %></small>
      <small><%= link_to "Destroy", "#" %></small>
    </p>
  </div>
<% end %>

app/views/documents/new.html.erb
<h1 style="text-align: center">Upload</h1>
<% provide(:button_text, "Upload my document") %>
<%= render "profile-form" %>

app/views/documents/show.html.erb
<h1>Document</h1>

<!-- use .card instead of .panel -->
<div class="row justify-content-center">
  <div class="col-3">
    <%= image_tag @document.file_name.preview(size: "50x50"), style: "width: 300px; height: 420px" %>
  </div>
  <div class="col-3">
    <p>Description: <%= @document.description %></p>
    <p>Author: <%= @document.author %></p>
    <p>Category: <%= @document.categories.pluck(:category).join(", ") %></p>
    <p><%= link_to "Edit this document", edit_document_path(@document) %></p>
    <p><%= link_to "Download this document", download_pdf_document_path(@document), target: "blank" %></p>
    <p><%= link_to "Delete this document", document_path(@document), method: :delete, data: {confirm: "U sure?"} %></p>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-6">
    <% if @is_read %>
      <p>You have viewed this document <%= @history.counter %> times</p>
    <% end %>

    <% if @is_downloaded %>
      <p>This document has been downloaded <%= @downloaded_time.count %> times</p>
    <% end %>

    <h3>People who viewed this document</h3>
    <p><%= @document.users.pluck(:name).join(", ") %></p>

    <h3>People who have downloaded this document</h3>
    <p><%= @document.downloaders.pluck(:name).join(", ") %></p>
    <hr>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-6">
    <h2>Comments</h2>
    <% @document.comments.each do |c| %>
      <div class="card">
        <div class="card-body">
          <span><%# image_tag c.user.avatar.preview(size: "50x50"), style: "width: 50px; height: 50px" %></span>
          <h3><%= link_to c.user.name, user_path(c.user), class: "badge badge-dark" %></h3>
          <p><%= c.content %></p>
          <% if c.user == current_user %>
            <p>
              <small><%= link_to "Edit", edit_comment_path %></small>
              <small><%= link_to "Delete", c, method: :delete, data: {confirm: "Are you sure?"} %></small>
            </p>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= form_for(@document.comments.build(user: current_user)) do |f| %>
      <%= f.label :content %>
      <%= f.text_field :content, class: "form-control" %>

      <%= hidden_field_tag :document_id, @document.id %>

      <%= f.submit "Comment", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>