config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"

  resources :users do
    member do
      get "friendlist", as: "friendlist"
    end
    member do
      get "viewed_documents"
    end
    member do
      get "downloaded_documents"
    end
  end

  resources :documents do
    member do
      get "download_pdf"
    end
  end
  
  resources :comments
  resources :requests
  resources :histories
  resources :categories
  resources :category_relationships
  resources :follow_relationships
  resources :favorites, only: [:create, :destroy]

  namespace :admin do
    resources :requests, only: [:index, :update]
    resources :users do
      member do
        patch :update_role, as: "update_role"
        get "reason", as: "reason"
      end
    end
  end

  root "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :category_relationships
  has_many :documents, through: :category_relationships
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :document
  belongs_to :user
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  has_many :category_relationships
  has_many :categories, through: :category_relationships
  has_many :comments
  has_many :downloaded_times
  has_many :downloaders, through: :downloaded_times, source: :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user
  has_many :histories
  has_many :users, through: :histories

  has_one_attached :file_name

  belongs_to :user

  acts_as_paranoid

  validate :correct_document_mime_type

  private

  def correct_document_mime_type
    if file_name.attached? && !file_name.content_type.in?(%w(application/pdf))
      file_name.purge
      errors.add(:file_name, 'Must be a PDF file')
    end
  end

end

app/models/downloaded_time.rb
# frozen_string_literal: true

class DownloadedTime < ApplicationRecord
  belongs_to :document
  belongs_to :user
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :document
  belongs_to :user
end

app/models/follow_relationship.rb
# frozen_string_literal: true

class FollowRelationship < ApplicationRecord
  scope :not_yet_accepted, -> { where.not(status: "accepted") }

  belongs_to :following, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/history.rb
# frozen_string_literal: true

class History < ApplicationRecord
  belongs_to :document
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true,
                      uniqueness: {message: "You have already sent your request"}
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :comments
  has_many :documents
  has_many :favorites
  has_many :favorite_documents, through: :favorites, source: :document
  has_many :follow_relationships
  has_many :histories
  has_many :viewed_documents, through: :histories, source: :document
  has_many :downloaded_times
  has_many :downloaded_documents, through: :downloaded_times, source: :document
  has_many :requests

  has_many :active_relationships, class_name: "FollowRelationship",
                                foreign_key: :following_id,
                                dependent: :destroy
  has_many :followed, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "FollowRelationship",
                                 foreign_key: :followed_id,
                                 dependent: :destroy
  has_many :following, through: :passive_relationships, source: :following

  has_many :active_friends, -> {where(status: "accepted")},
                            class_name: "FollowRelationship",
                            foreign_key: :following_id
  has_many :followed_friends, through: :active_friends, source: :followed
  has_many :passive_friends, -> {where status: "accepted"},
                             class_name: "FollowRelationship",
                             foreign_key: :followed_id
  has_many :following_friends, through: :passive_friends, source: :following


  has_one_attached :avatar

  acts_as_paranoid

  validates :name, presence: true, length: {maximum: 100}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 120},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create, :friendlist, :index]
  before_action :correct_user, only: [:edit, :update]
  before_action :check_admin, only: [:destroy]
  skip_before_action :check_if_logged_in, only: [:new, :create]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      log_in @user
      redirect_to @user
      flash[:success] = "Welcome to the gang"
    else
      render "new"
    end
  end

  def edit
    #code
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
      flash[:success] = "Profile updated"
    else
      redirect_to @user
      flash[:danger] = "Profile note updated"
    end
  end

  def show
    @user = User.find(params[:id])
    @viewed_documents = @user.viewed_documents
    @friend_request = current_user.active_relationships.find_by(following_id: current_user.id,
                                                                followed_id: @user.id)
    @downloaded_documents = current_user.downloaded_documents
  end

  def destroy
    #code for banning?
  end

  def friendlist
    @friends = current_user.following_friends + current_user.followed_friends
  end

  def viewed_documents
    @viewed_documents = @user.viewed_documents.paginate(
      page: params[:page],
      per_page: 24
    )
  end

  def downloaded_documents
    @downloaded_documents = @user.downloaded_documents.paginate(
      page: params[:page],
      per_page: 24
    )
  end
  private

  def users_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    unless @user == current_user
      respond_to do |format|
        format.html {redirect_to users_url, notice: "Mind your own business boi"}
      end
    end
  end

  def check_admin
    unless current_user.role == "admin"
      redirect_to root_path
      flash[:danger] = "Fuck off"
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_admin-button.html.erb
<% if current_user.role == "admin" %>
  <button type="button" class="btn btn-success">Admin</button>
<% elsif current_user.role == "user" %>
  <% if current_user.requested == nil %>
    <%= link_to "Become an admin", requests_path, class: "btn btn-primary", method: :post %>
  <% elsif current_user.requested == "pending" || current_user.requested == "not_yet_rejected" %>
    <button type="button" class="btn btn-info"></button>
  <% elsif current_user.requested == "rejected" %>
    <!-- <h3>You have been rejected</h3> -->
    <%= link_to "Become an admin", requests_path, class: "btn btn-primary", method: :post %>
  <% end %>
<% end %>

app/views/layouts/_nav-bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Project 1", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <% unless logged_in? %>
        <li>
          <%= link_to "Sign up", new_user_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
        </li>
        <li>
          <%= link_to "Upload a document", new_document_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "All users", users_path, class: "nav-link" %>
        </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Documents I have viewed", viewed_documents_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Documents I have downloaded", downloaded_documents_user_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Your friends", friendlist_user_path(current_user), class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <% end %>
    <% if logged_in? %>
      <form class="form-inline my-2 my-lg-0">
        <%= render "layouts/admin-button" %>
      </form>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav-bar" %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>